# Generated by Django 4.2.3 on 2023-08-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
