# Generated by Django 4.2.3 on 2023-09-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_video'),
        ('orders', '0002_copon_end_date_copon_percentage_copon_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='oder',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='products.product'),
            preserve_default=False,
        ),
    ]
