# Generated by Django 4.2.3 on 2023-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartdetail_oder_cartdetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='price',
        ),
    ]
