# Generated by Django 4.2.3 on 2023-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_cart_user_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
