# Generated by Django 4.2.3 on 2023-09-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product-plural'},
        ),
    ]
