# Generated by Django 4.2.3 on 2023-10-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
