# Generated by Django 4.2.3 on 2023-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_rating_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(max_length=30000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=30000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_de',
            field=models.TextField(max_length=600, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(max_length=600, null=True, verbose_name='subtitle'),
        ),
    ]
